version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "888:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
  php:
    build: ./docker/php
    container_name: php-fpm
    volumes:
      - ./src:/var/www/laravel
  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - ./docker/pgsql/db.env
    volumes:
      - ./db-data:/var/lib/postgresql/data