version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
#      - ./src/storage/app:/var/www/laravel/storage/app:ro
#      - ./src/public:/var/www/laravel/public:ro
  php:
    build: ./docker/php
    container_name: php-fpm
    volumes:
      - ./src:/var/www/laravel
  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - ./docker/pgsql/db.env
    volumes:
      - ./db-data:/var/lib/postgresql/data
#  whisper:
#    image: onerahmet/openai-whisper-asr-webservice
#    ports:
#      - "9001:9000"
#    environment:
#      - ASR_MODEL=base
#      - ASR_ENGINE=openai_whisper
#    volumes:
#      - ./src:/var/www/laravel